---
title: "Module2"
author: "David Gao"
output: html_document
---

```{r setup, include = FALSE}
library("ggplot2")
library("readxl")
Bodyfat <- read.csv("BodyFat.csv")
summary(Bodyfat)
```
```{r}
BFvsAll <- lm(BODYFAT~DENSITY+AGE+WEIGHT+HEIGHT+ADIPOSITY+NECK+CHEST+ABDOMEN+HIP+THIGH+KNEE+ANKLE+BICEPS+FOREARM+WRIST, data = Bodyfat)
summary(BFvsAll)#R^2 is 97.87%, but definitely has overfitting problem
#ggplot of these two graph shows that BODYFAT has strong correlation with WEIGHT
ggplot(Bodyfat,aes(WEIGHT,BODYFAT))+geom_jitter()
ggplot(Bodyfat,aes(WEIGHT,BODYFAT))+geom_jitter(aes(x = WEIGHT,y = BODYFAT, color = WEIGHT, size = BODYFAT))
```
```{r}
#HEIGHT seems has weak relation with BODYFAT
ggplot(Bodyfat,aes(HEIGHT,BODYFAT))+geom_jitter()
ggplot(Bodyfat,aes(HEIGHT,BODYFAT))+geom_jitter(aes(x = HEIGHT,y = BODYFAT, color = HEIGHT, size = BODYFAT))
```
```{r}
#ggplots shows that BODYFAT has strong correlation with ABDOMEN
ggplot(Bodyfat,aes(ABDOMEN,BODYFAT))+geom_jitter()
ggplot(Bodyfat,aes(ABDOMEN,BODYFAT))+geom_jitter(aes(x = ABDOMEN,y = BODYFAT, color = ABDOMEN, size = BODYFAT))
```
```{r}
#ggplots shows that BODYFAT has weak correlation with AGE
ggplot(Bodyfat,aes(AGE,BODYFAT))+geom_jitter()
ggplot(Bodyfat,aes(AGE,BODYFAT))+geom_jitter(aes(x = AGE,y = BODYFAT, color = AGE, size = BODYFAT))
```