---
title: "Body Fat Analysis"
author: "Marwan Lloyd"
date: '2022-10-07'
output: html_document
---

```{r setup, include=FALSE}
library(car)
#setWD for wherever bodyfat csv is on machine 
#setwd("~/Desktop/UW-Madison/Stat 628/Module 2 Starter Materials")
body_fat <- read.csv('../Data/adjusted_bodyfat.csv')
#convert to KGs
body_fat$WEIGHT <- (body_fat$WEIGHT/2.2)
#convert to CMs
body_fat$HEIGHT <- body_fat$HEIGHT * 2.54
```

```{r}
sort(unique(body_fat$BODYFAT)) # <- from this we see some body fat numbers make no sense
```

```{r}
#remove ID column remove density column, and remove adiposity as that's weight/height and keeping it could lead to multicollinearity issues
adjusted_body_fat <- body_fat[c(2,4,5,6,8:17),]

adjusted_body_fat_lm <- lm(adjusted_body_fat$BODYFAT ~ . , adjusted_body_fat)
summary(adjusted_body_fat_lm)
```

```{r}
#Get VIF's
# VIFs start at 1 and have no upper limit. A value of 1 indicates that there is no correlation between this independent variable and any others. VIFs between 1 and 5 suggest that there is a moderate correlation, but it is not severe enough to warrant corrective measures. VIFs greater than 5 represent critical levels of multicollinearity where the coefficients are poorly estimated, and the p-values are questionable.

vif(adjusted_body_fat_lm)
```

```{r}
#remove high p-value variables (higher than .2)
#so  remove height, chest, knee, ankle, biceps
#remaining variables are: age, weight, neck, abdomen, hip, thigh, forearm, wrist
bf_2 <- adjusted_body_fat[c(1:3,5,7,8,9,13,14)]
fit_2 <- lm(BODYFAT ~ . , bf_2)
summary(fit_2)
```

```{r}
#proposing models
#for simplicity this model is good as it's only 3 variables that are easy to get 
#Is better than just Age + Weight as it's R^2 is .3 higher 
#R^2 is only .02 less than fit_2's R^2
summary(lm(BODYFAT ~ AGE + WEIGHT + ABDOMEN, bf_2))
```

```{r}
#proposing model 2 
#simpler but loses a lot of accuracy by missing one variable
summary(lm(BODYFAT ~ AGE + WEIGHT, bf_2))
```

```{r}
#Model w/ 3 most statistically significant values but is less accurate than Age + weight + abdomen
summary(lm(BODYFAT ~ FOREARM + WRIST + ABDOMEN, body_fat))
```

```{r}
#proposing model 4
#Seems like best
#highest R^2 of proposed ones w/ .7187 
#lower standard error than AGE + WEIGHT + ABDOMEN
summary(lm(BODYFAT ~ WEIGHT + ABDOMEN, body_fat))
```


```{r FIRST GO}
library(shiny)
ui <- fluidPage(
selectInput("stat_dropdown", "Select a Stat of interest", choices = colnames(body_fat)[3:17], multiple = FALSE),
plotOutput("general_scatter")
)

server <- function(input, output) { 
  output$general_scatter <-  renderPlot({ 
  ggplot(body_fat,aes(input$stat_dropdown,BODYFAT)) + 
      labs(x = input$stat_dropdown, y = "Body Fat", title = "Body Fat Scatterplot") +
     geom_jitter(aes(x = input$stat_dropdown,y = BODYFAT, color = input$stat_dropdown, size = BODYFAT))
})
  }

app <- shinyApp(ui, server)

app
```


```{r REAL TRY}
library(shiny)
library(shinythemes)

ui <- 
  navbarPage("Group 2 Shiny", collapsible = TRUE, inverse = TRUE, theme = shinytheme("spacelab"),
#             tabPanel("All Stat Scatterplots",
#                      fluidPage(
#                      selectInput("stat_dropdown", "Select a Stat of Interest", #choices = colnames(body_fat)[3:17], multiple = FALSE),
#                      plotOutput("general_scatter")
#                      )),
             tabPanel("Model Calculator",
                      tags$p("The model that our project decided to use was a multi-linear regression of bodyfat percentage on two variables: weight and abdomen circumfrence. The final equation (used in this calculator) determined for this regression was:"), tags$h3("Body Fat % = -40.47 - .67*Weight + .91 * Abdomen"), tags$h4("---------------------------------------------------------"),
                      sidebarLayout(sidebarPanel(numericInput("Weight", "Weight (in kg):", 0, min = 0, step = .01), numericInput("Abdomen", "Abdomen Circumfrence (in cm):", 0, min = 0, step = .01)),
                        mainPanel("Calculated Bodyfat:", textOutput("calculated_bodyfat"), tags$head(tags$style("#calculated_bodyfat{color: black;
                                 font-size: 20px;
                                 font-style: bold;
                                 }"
                         )
              )))
                      ),
             tabPanel("About", tags$p("This shiny app is maintained by Marwan Lloyd '23. For any questions, concerns, or feedback please reach out him at either of the below emails:"), tags$address("Marwan.Lloyd@Wisc.edu"), tags$address("Melloyd2@Wisc.edu"))
)

server <- function(input, output) { 
  
  observeEvent(input$Weight,{
    if(input$Weight < 0 || isTRUE(is.na(input$Weight)) ){ 
      x <- 0}
    else{
      x <- input$Weight
    }
    updateNumericInput(getDefaultReactiveDomain(), "Weight", value = round(x,digits = 2))})
  
  observeEvent(input$Abdomen,{
    if(input$Abdomen < 0 || isTRUE(is.na(input$Abdomen)) ){ 
      y <- 0}
    else{
      y <- input$Abdomen
    }
    updateNumericInput(getDefaultReactiveDomain(), "Abdomen", value = round(y,digits = 2))})
  
  output$calculated_bodyfat <- renderText(paste(c(round(-40.47 - .673*input$Weight + .91 * input$Abdomen,2)),"%"))
  
  output$general_scatter <-  renderPlot({ 
  ggplot(body_fat,aes(input$stat_dropdown,BODYFAT)) + 
      labs(x = input$stat_dropdown, y = "Body Fat", title = "Body Fat Scatterplot") +
     geom_jitter(aes(x = input$stat_dropdown,y = BODYFAT, color = input$stat_dropdown, size = BODYFAT))
})
  }

shinyApp(ui = ui, server = server)
```


